Experiment No. - 9

Name : Pranav Menon\
PRN No. : 25070123085\
Batch : ENTC B1

Aim of the experiment : To Study Numpy Tool in Python

In [21]:
# Declaration of a numpy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
#Dimensions of an Array
print(a.ndim)
print(b.ndim)

1
2


In [16]:
#Size of an Array
print(a.size)
print(b.size)

7
9


In [18]:
#Shape of an Array
print(a.shape)
print(b.shape)

(7,)
(3, 3)


In [23]:
#To determine the datatype of an array
print(a.dtype)
print(b.dtype)
import numpy as np
a = np.array([1,10,20,30.5,40,50,500])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.dtype)
print(b.dtype)

float64
int64
float64
int64


In [34]:
#In-Built functions of an Array
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# In-Built Functions of an Array
print(np.arange(1,10,2))
print(np.arange(1,11,2))
print(np.linspace(0,1,4))
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(b*2)
print(a+5)

[1 3 5 7 9]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]


In [47]:
# In-Built Functions of an Array
print(np.mean(a))
print(np.median(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))

93.0
30.0
500
1
651
